---
# dotfiles_personal.yml
#
# Deploys personalized dotfiles to jump hosts
# Contains full-featured configuration for interactive work

- name: Deploy personal dotfiles to pi_omv hosts
  hosts: pi_omv
  become: true
  vars:
    users:
      - pbh
  tasks:
    - name: Find all dotfiles in personal directory
      find:
        paths: "{{ inventory_dir }}/files/personal"
        patterns: ".*"
        hidden: true
      register: dotfiles_found
      delegate_to: localhost
      become: false

    - name: Copy personal dotfiles for each user
      copy:
        src: "{{ item[1].path }}"
        dest: "/home/{{ item[0] }}/{{ item[1].path | basename }}"
        owner: "{{ item[0] }}"
        group: "{{ item[0] }}"
        mode: "0644"
        backup: true
      loop: "{{ users | product(dotfiles_found.files) | list }}"
